package SwingGenerico.Generico;

import SwingGenerico.Interfaces.PainelGenerico;
import com.google.gson.JsonObject;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Efraim
 */
public class CadastrarPainelGenerico extends javax.swing.JPanel implements PainelGenerico{

    /**
     * Creates new form JPanelGenerico
     */
    int x0 = 10, y0 = 10;
    String nome = "Nome";
    public CadastrarPainelGenerico() {
        initComponents();
        nomeInvalidoLabel.setVisible(false);
        this.redimensionar();
    }
    public CadastrarPainelGenerico(String nome) {
        this();
        this.setNome(nome);
        this.redimensionar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeLabel = new javax.swing.JLabel();
        TextField = new javax.swing.JTextField();
        nomeInvalidoLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(160, 60));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(null);

        nomeLabel.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        nomeLabel.setText("Nome:");
        add(nomeLabel);
        nomeLabel.setBounds(10, 10, 35, 16);

        TextField.setPreferredSize(new java.awt.Dimension(6, 24));
        TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldFocusLost(evt);
            }
        });
        TextField.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                TextFieldComponentResized(evt);
            }
        });
        add(TextField);
        TextField.setBounds(50, 10, 100, 24);

        nomeInvalidoLabel.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        nomeInvalidoLabel.setForeground(new java.awt.Color(255, 0, 0));
        nomeInvalidoLabel.setText("Nome Inválido");
        add(nomeInvalidoLabel);
        nomeInvalidoLabel.setBounds(50, 40, 100, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TextFieldComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldComponentResized

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        TextField.setBounds(TextField.getX(), TextField.getY(), this.getWidth() - (nomeLabel.getX() + nomeLabelSize()) - 10, 26);
    }//GEN-LAST:event_formComponentResized

    private void TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFocusLost

    @Override
    public String getNome() {
        return nome;
    }
    
    public void setNome(String novoNome) {
        this.nome = novoNome;
        this.renomearLabels();
    }
    public void setCustomMsgInvalido(String msgErro) {
        nomeInvalidoLabel.setText(msgErro);
        this.redimensionar();
    }
    private void renomearLabels() {
        nomeLabel.setText(String.format("%s:", nome));
        nomeInvalidoLabel.setText(String.format("%s Inválido", nome));
        this.redimensionar();
    }
    private int nomeLabelSize() {
        return (nomeLabel.getText().length()*7) + 3;
    }
    private int nomeInvalidoLabelSize() {
        return nomeInvalidoLabel.getText().length()*7;
    }
    private int TextFieldSize() {
        return TextField.getWidth();
    }
    private void redimensionar() {
        nomeLabel.setBounds(x0, y0, this.nomeLabelSize(), 14);
        nomeInvalidoLabel.setBounds(x0 + this.nomeLabelSize() + 5, y0 + 30, this.nomeInvalidoLabelSize(), 14);
        TextField.setBounds(x0 + this.nomeLabelSize() + 5, TextField.getY(), this.getWidth() - (nomeLabel.getX() + nomeLabelSize()) - 10, 26);
    }
    public void mostrarMensagemErro(boolean visivel) {
        nomeInvalidoLabel.setVisible(visivel);
    }
    @Override
    public boolean painelPreenchido() {
        if (!TextField.getText().equals("")) {
            this.mostrarMensagemErro(false);
            return true;
        } else {
            this.mostrarMensagemErro(true);
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField;
    private javax.swing.JLabel nomeInvalidoLabel;
    private javax.swing.JLabel nomeLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addInput(JsonObject jsonObj) {
        jsonObj.addProperty(this.nome, TextField.getText());
    }
}
