package SwingGenerico.Generico;


import SwingGenerico.BancoDeDados.BancoDeDados;
import SwingGenerico.Interfaces.PainelGenerico;
import com.google.gson.JsonObject;
import java.awt.Component;
import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.HashMap;
import java.lang.reflect.Constructor;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Group;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Efraim
 */
public class CadastrarGenerico extends javax.swing.JFrame{

    /**
     * Creates new form JFrameGenerico
     */
    private String nome;
    private Class classe;
    private HashMap<String,PainelGenerico> components = new HashMap();
    public CadastrarGenerico() {
        initComponents();
        this.setNome("Cadastrar");
        tituloLabel.setText("Cadastrar");
        finalizarButton.setText("Cadastrar");
        
    }
    public CadastrarGenerico(String funcaoTela) {
        initComponents();
        this.setNome(funcaoTela);
        tituloLabel.setText(funcaoTela);
        finalizarButton.setText(funcaoTela);
    }
    public CadastrarGenerico(String funcaoTela, PaineisGenericos paineis) {
        this(funcaoTela);
        this.classe = paineis.getClasse();
        
        GroupLayout layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(layout);
        
        layout.setAutoCreateContainerGaps(true);
        layout.setAutoCreateGaps(true);
        
        //Creating and defining horizontal group
        Group horizontalGroup = layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        
        for (PainelGenerico i : paineis.getPaineis()) {
            horizontalGroup.addComponent((Component) i);
        }
        
        layout.setHorizontalGroup(horizontalGroup);
        
        //Creating and defining vertical group
        Group verticalGroup = layout.createSequentialGroup();
        
        for (PainelGenerico i : paineis.getPaineis()) {
            verticalGroup.addComponent((Component) i);
        }
        
        layout.setVerticalGroup(verticalGroup);
        
        /*
        this.components = paineis.getPaineis();
        for (String i : paineis.getPaineisNomes()) {
            jPanel1.add((Component) this.components.get(i));
        }
        */
        validate();
        repaint();
    }
    public CadastrarGenerico(String funcaoTela, String finalizarButtonName, PaineisGenericos paineis) {
        this(funcaoTela, paineis);
        finalizarButton.setText(finalizarButtonName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        finalizarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tituloPanel.setBackground(new java.awt.Color(51, 213, 213));

        tituloLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("jLabel1");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        finalizarButton.setBackground(new java.awt.Color(40, 200, 40));
        finalizarButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        finalizarButton.setText("jButton1");
        finalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarButtonActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(finalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void finalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarButtonActionPerformed
        if (this.validarPaineis()) {
            try {
                System.out.println(BancoDeDados.getInstance().criarObject(classe.cast(this.CriarInstancia()), classe));
            } catch (InstantiationException ex) {
                ex.printStackTrace();
            } catch (IllegalAccessException ex) {
                ex.printStackTrace();
            } catch (IllegalArgumentException ex) {
                ex.printStackTrace();
            } catch (InvocationTargetException ex) {
                ex.printStackTrace();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            this.dispose();
        }
    }//GEN-LAST:event_finalizarButtonActionPerformed

    public String getNome() {
        return this.nome;
    }
    private void setNome(String nome) {
        this.nome = nome;
    }
    private boolean validarPaineis() {
        boolean validado = true;
        for (PainelGenerico i : components.values()) {
            if (!i.painelPreenchido()) {
                validado = false;
            }
        }
        return validado;
    }
    public JsonObject output() {
        JsonObject ans = new JsonObject();
        for (PainelGenerico i : this.components.values()) {
            i.addInput(ans);
        }
        return ans;
    }
    private Object CriarInstancia() throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException {
        return this.getConstrutor().newInstance(this.output());
    }
    private Constructor getConstrutor() throws InstantiationException {
        Constructor[] aux = this.classe.getConstructors();
        for (Constructor i : aux) {
            if (i.getParameterCount() == 1) {
                return i;
            }
        }
        throw new InstantiationException("No Constructor with only one parameter was found.");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarGenerico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finalizarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables
}
